
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: Europe/Istanbul

